TOOL_DESCRIPTIONS = {
    "work_get": "Use this when you need configured work metadata.",
    "work_update": "Use this when you need to update the work title.",
    "world_fact_create": "Use this when you need to create a normalized world fact.",
    "world_fact_update": "Use this when you need to edit a world fact safely.",
    "world_fact_get": "Use this when you need one normalized world fact.",
    "world_fact_search": "Use this when you need Japanese world-fact substring search.",
    "timeline_event_create": "Use this when you need a dated timeline event.",
    "timeline_event_update": "Use this when you need to edit a timeline event.",
    "timeline_event_get": "Use this when you need one timeline event and participants.",
    "timeline_event_search": "Use this when you need timeline text search.",
    "timeline_range": "Use this when you need timeline range-overlap search.",
    "timeline_move": "Use this when you need to move an event to an exact day.",
    "timeline_relation_create": "Use this when you need a directed event relation.",
    "character_create": "Use this when you need a human, AI, or organization profile.",
    "character_update": "Use this when you need to edit a character profile.",
    "character_get": "Use this when you need one normalized character profile.",
    "character_search": "Use this when you need Japanese character substring search.",
    "relationship_create": "Use this when you need a directed character relationship.",
    "relationship_update": "Use this when you need to edit a relationship.",
    "relationship_search": "Use this when you need character relationship search.",
    "canon_status_set": "Use this when you need an explicit canon transition.",
    "canon_decision_get": "Use this when you need one canon decision snapshot.",
    "canon_decision_search": "Use this when you need canon decision search.",
}
