from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from novel_core.style_analysis.runtime_models import (
    AnalyzerDefinition,
    DependencySpec,
)

ANALYZERS: tuple[AnalyzerDefinition, ...] = (
    AnalyzerDefinition(
        id="scene-boundary-detector",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(),
        state_inputs=(),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="entity-mention-extractor",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(),
        state_inputs=(),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="entity-resolver",
        version=1,
        deterministic=None,
        cacheable=False,
        dependencies=(
            DependencySpec(
                analyzer_id="entity-mention-extractor",
                mode="subject_partial_allowed",
            ),
        ),
        state_inputs=("entity_registry_state",),
        policy_inputs=("entity_resolution_auto_merge",),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="speaker-attribution",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(
            DependencySpec(
                analyzer_id="entity-resolver",
                mode="subject_partial_allowed",
            ),
        ),
        state_inputs=("mention_resolution",),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="term-candidate-extractor",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(),
        state_inputs=(),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="term-resolver",
        version=1,
        deterministic=None,
        cacheable=False,
        dependencies=(
            DependencySpec(
                analyzer_id="term-candidate-extractor",
                mode="subject_partial_allowed",
            ),
        ),
        state_inputs=("term_registry_state",),
        policy_inputs=("term_resolution_auto_merge",),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="term-explanation-detector",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(
            DependencySpec(
                analyzer_id="term-resolver",
                mode="subject_partial_allowed",
            ),
        ),
        state_inputs=(),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="scene-semantic-classifier",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(),
        state_inputs=(),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="block-semantic-classifier",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(),
        state_inputs=(),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="pov-classifier",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(
            DependencySpec(
                analyzer_id="entity-resolver",
                mode="subject_partial_allowed",
            ),
        ),
        state_inputs=("mention_resolution",),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="style-metrics-basic",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(),
        state_inputs=(),
        policy_inputs=(),
        input_scope=None,
    ),
    AnalyzerDefinition(
        id="style-metrics-semantic",
        version=1,
        deterministic=None,
        cacheable=True,
        dependencies=(
            DependencySpec(
                analyzer_id="speaker-attribution",
                mode="subject_partial_allowed",
            ),
            DependencySpec(
                analyzer_id="term-resolver",
                mode="subject_partial_allowed",
            ),
            DependencySpec(
                analyzer_id="term-explanation-detector",
                mode="subject_partial_allowed",
            ),
            DependencySpec(
                analyzer_id="block-semantic-classifier",
                mode="subject_partial_allowed",
            ),
        ),
        state_inputs=(
            "metric_effective_state",
            "term_first_appearance",
        ),
        policy_inputs=(
            "speaker_effective",
            "term_explanation_effective",
            "block_semantic_effective",
        ),
        input_scope=None,
    ),
)

ANALYZERS_BY_ID: Mapping[str, AnalyzerDefinition] = MappingProxyType(
    {analyzer.id: analyzer for analyzer in ANALYZERS}
)
